'use server';
/**
 * @fileOverview A sales forecasting AI agent for MediaFlow.
 *
 * - salesForecastGeneration - A function that handles the sales forecast generation process.
 * - SalesForecastGenerationInput - The input type for the salesForecastGeneration function.
 * - SalesForecastGenerationOutput - The return type for the salesForecastGeneration function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Input schema for the public facing function and flow
const SalesForecastGenerationInputSchema = z.object({
  historicalProjects: z.array(z.object({
    projectName: z.string().describe('Name of the historical project.'),
    clientName: z.string().describe('Name of the client for this project.'),
    revenue: z.number().describe('Total revenue generated by the project.'),
    startDate: z.string().describe('Start date of the project in YYYY-MM-DD format.'),
    endDate: z.string().describe('End date of the project in YYYY-MM-DD format.'),
    status: z.string().describe('Current status of the project (e.g., Completed, In Progress, Canceled).'),
  })).describe('Array of historical project data.'),
  clients: z.array(z.object({
    clientName: z.string().describe('Name of the client.'),
    industry: z.string().describe('Industry of the client.'),
    pastProjectCount: z.number().describe('Number of past projects completed for this client.'),
  })).describe('Array of client information.'),
  forecastPeriodInWeeks: z.number().min(1).max(52).describe('Number of weeks into the future for the sales forecast (1-52 weeks).'),
});
export type SalesForecastGenerationInput = z.infer<typeof SalesForecastGenerationInputSchema>;

// Output schema for the public facing function and flow
const SalesForecastGenerationOutputSchema = z.object({
  forecasts: z.array(z.object({
    period: z.string().describe('The forecast period, e.g., "Week 1", "2024-W25".'),
    projectedRevenue: z.number().describe('The projected revenue for this period.'),
    confidenceLevel: z.enum(['High', 'Medium', 'Low']).describe('Confidence level of the forecast for this period.'),
    explanation: z.string().describe('A brief explanation for the forecast of this period.'),
  })).describe('An array of weekly sales forecasts.'),
  overallSummary: z.string().describe('An overall summary of the entire forecast period, highlighting key insights, opportunities, and potential challenges.'),
});
export type SalesForecastGenerationOutput = z.infer<typeof SalesForecastGenerationOutputSchema>;

// Extend the input schema for the prompt to include formatted strings
const SalesForecastPromptInputSchema = SalesForecastGenerationInputSchema.extend({
  historicalProjectsFormatted: z.string().describe('Pre-formatted string of historical project data for embedding in the prompt.'),
  clientsFormatted: z.string().describe('Pre-formatted string of client information for embedding in the prompt.'),
});

// Wrapper function to be exported and called by Next.js React code
export async function salesForecastGeneration(input: SalesForecastGenerationInput): Promise<SalesForecastGenerationOutput> {
  return salesForecastGenerationFlow(input);
}

// Define the Genkit prompt
const salesForecastGenerationPrompt = ai.definePrompt({
  name: 'salesForecastGenerationPrompt',
  input: { schema: SalesForecastPromptInputSchema }, // Use the extended schema for the prompt
  output: { schema: SalesForecastGenerationOutputSchema },
  prompt: `You are an expert sales forecaster for a media production company called MediaFlow. Your task is to analyze the provided historical project data and client information to generate a detailed sales forecast for the next {{forecastPeriodInWeeks}} weeks.

Consider market trends, client history, project revenue, project duration, and project status when making your predictions. Assume that current economic conditions are stable unless specified in the project data. Focus on identifying potential revenue streams, risks, and client-specific trends.

Historical Project Data:
{{{historicalProjectsFormatted}}}

Client Information:
{{{clientsFormatted}}}

Based on this data, provide a weekly sales forecast. For each week, include the forecast period (e.g., "Week 1", "2024-W25"), the projected revenue in USD, a confidence level (High, Medium, Low), and a brief explanation for the forecast. Finally, provide an overall summary of the entire forecast period, highlighting key insights, opportunities, and potential challenges in the sales pipeline.`,
});

// Define the Genkit flow
const salesForecastGenerationFlow = ai.defineFlow(
  {
    name: 'salesForecastGenerationFlow',
    inputSchema: SalesForecastGenerationInputSchema,
    outputSchema: SalesForecastGenerationOutputSchema,
  },
  async (input) => {
    // Format historical projects data into a readable string
    const historicalProjectsFormatted = input.historicalProjects.map(project =>
      `- Project: "${project.projectName}", Client: "${project.clientName}", Revenue: $${project.revenue}, Start Date: ${project.startDate}, End Date: ${project.endDate}, Status: ${project.status}`
    ).join('\n'); // Use actual newlines for better readability in the prompt

    // Format client information into a readable string
    const clientsFormatted = input.clients.map(client =>
      `- Client: "${client.clientName}", Industry: "${client.industry}", Past Projects: ${client.pastProjectCount}`
    ).join('\n'); // Use actual newlines for better readability in the prompt

    // Prepare the input object for the prompt, including the formatted strings
    const promptInput = {
      ...input,
      historicalProjectsFormatted,
      clientsFormatted,
    };

    // Call the prompt with the prepared input
    const { output } = await salesForecastGenerationPrompt(promptInput);

    // Return the output from the prompt
    return output!;
  }
);
